server:
  port: 8082
  
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:hungerbuddyauth
    driverClassName: org.h2.Driver
    password: 
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
eureka:
  client:
     register-with-eureka: true
     fetch-registery: true
     service-url:
       default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
