server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   

spring:
 cloud:
   gateway:
     discovery:
       locator:
         enabled: true
         lowerCaseServiceId: true
    
